### ISSUE TITLE
What's the benefit for this?

### ISSUE THREAD

**Issue by Swoorup** [thrasher-/gocryptotrader#184]
Between this and other bots like gekko, zenbot, and other zillions?

**Comment by thrasher-** [comment]
Our goal is a golang framework and a one stop solution to trade digital currencies. Whether that means using the supplied web GUI or writing your own trade logic based off the framework. Portfolio address tracking, tax reporting, many exchanges supported (compared to zenbot), forex conversion are some unique features which we are working on or have already completed. For discussions around the project, it's best to use our Slack instead of lodging this in the issue section.
