### ISSUE TITLE
Webserver stopped working

### ISSUE THREAD

**Issue by jeee** [thrasher-/gocryptotrader#296]
an update during the last few months broke the webserver. http://127.0.0.1:9050/ now gives a 404

**Comment by xtda** [comment]
This should have been fixed under #292 have you pulled latest code from repo recently?

**Comment by jeee** [comment]
that error was on a fresh checkout

**Comment by klebed** [comment]
@jeee I think the concept of that application isn't that clear. You might expect it to serve web-interface, while it's seems not. It serves only web-api, while we-interface are made separately and author suggest using it rather by angular-serve for development, or electron, or by nginx by config provided.
I'm sure it is misconception and worsened user experience, but it is how it is.

I believe there should be static served by gorilla out of the box, though...

**Comment by klebed** [comment]
@jeee  you should properly set hostname at config.Webserver.ListenAddress

**Comment by xtda** [comment]
This is caused by thrasher-/gocryptotrader/restful_router.go#L126

ListenAddress in a default config is set to ":9050" this causes the accepting host to be set on routes as ":9050" 

I will get a PR open up shortly that will change https://github.com/thrasher-/gocryptotrader/blob/master/restful_router.go#L54 to follow the same standard we have that if no value is set it will default to localhost

Meaning that under a default config the REST interface will accept connections on http://localhost:9050 unless configured differently

**Comment by jeee** [comment]
How to set it so it accepts everything? 0.0.0.0:9050 does not seem to work.

**Comment by xtda** [comment]
If you want to you can remove the Host call on https://github.com/thrasher-/gocryptotrader/blob/master/restful_router.go#L128

But this does come with risks such as opening you up to https://en.wikipedia.org/wiki/DNS_rebinding by accepting connections from any host
