### ISSUE TITLE
Rename config.dat to config.json for auto syntax highlighting

### ISSUE THREAD

**Issue by brunocassol** [thrasher-/gocryptotrader#48]
Having `.json` file extension makes it automatic for most editors to do syntax highlighting the config file.

![image](https://user-images.githubusercontent.com/203541/29997881-c7d3b882-8fec-11e7-8bac-d134cf200a87.png)

Just quality of life.

**Comment by joeblew99** [comment]
I am just starting on this. Cant see a default config file to get started. Is there one ?

**Comment by brunocassol** [comment]
Rename config_example.dat to config.dat

**Comment by joeblew99** [comment]
found it :)

Is there a way to pull historical data from the cli yet ?

**Comment by joeblew99** [comment]
there is no CLI :) Checked your roadmap and you dont have one. Would be really useful because it allows making it much easier to help develop. DO you want one ?

Also regarding the REST and websockets i am using protobuf and code generating all rest and websockets code with golang.
The rest / swagger one is here. Check the make file. Its pretty nice and will make it easier / faster
https://github.com/gedw99/metro

The protobuf to websockets is about 90% there. Will let you knwo if you like

**Comment by shazbert** [comment]
Will add it to the trello! Thanks  heaps @joeblew99 
Yes please let us know.

**Comment by joeblew99** [comment]
k.

**Comment by thrasher-** [comment]
Thanks for the suggestion, fixed in https://github.com/thrasher-/gocryptotrader/commit/ce908ee93901c38352baaf1b4f2cdd3c7a24cdec

By default the config file will be unencrypted and has a file extension of .json. If the user specifies to encrypt their config file; it will rename the config file to config.dat.
The bot will also check to see if the config is encrypted and uses config.dat, if it isn't, the bot will rename the config file to config.json. Conversely, if the bot uses config.json but is encrypted, the bot will rename the file to config.dat.
