### ISSUE TITLE
Error: yahoo returned zero currency data

### ISSUE THREAD

**Issue by uncentral** [thrasher-/gocryptotrader#77]
runs well until this error:

error
2018/01/08 19:28:09 Currency recv: {"query":{"count":0,"created":"2018-01-08T18:28:07Z","lang":"en-US","results":null}}
2018/01/08 19:28:09 Fatal error retrieving config currencies. Error: yahoo returned zero currency data

**Comment by thrasher-** [comment]
Unfortunately this is a random issue caused by Yahoo, their finance API use to work perfectly but now it occasionally doesn't return any currency data. In the latest version of GCT, it will switch the provider to 'fixer'.

You can also edit your config.json file as follows;

'CurrencyExchangeProvider": "fixer.

**Comment by daniel-cohen** [comment]
@thrasher- Sorry to comment on closed issue, but I believe yahoo blocked the forex service completely and you can remove the yahoo specific code.
See: https://stackoverflow.com/questions/5108399/yahoo-finance-all-currencies-quote-api-documentation

This is the best free alternative I've found:
https://free.currencyconverterapi.com/
